'use strict';
const canvas=document.querySelector('#moon'),start=document.querySelector('#start'),guide=document.querySelector('#guide'),hit=document.querySelector('#rotate'),letter=document.querySelector('#letter'),replay=document.querySelector('#replay'),note=document.querySelector('#load-note');
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const gl=canvas.getContext('webgl',{alpha:false,antialias:false,powerPreference:'low-power'});
let ready=false,active=false,openedAt=0,phase=0,progress=0,yaw=Math.PI/2,pitch=0,velX=0,velY=0,drag=null,last=0,raf=0,approach=null;
const clamp=(n,a=0,b=1)=>Math.max(a,Math.min(b,n));const smooth=t=>t*t*(3-2*t);
function fail(){document.querySelector('#error').hidden=false;note.textContent='请刷新后重试';}
if(!gl){fail();}else{boot();}
function boot(){
const vert='attribute vec2 a; varying vec2 uv; void main(){uv=a;gl_Position=vec4(a,0.,1.);}';
const frag=`precision highp float;
varying vec2 uv;uniform sampler2D map;uniform vec2 resolution;uniform float radius;uniform float cy;uniform float phase;uniform float opacity;uniform float yaw;uniform float pitch;
void main(){vec2 p=vec2(uv.x*resolution.x/resolution.y,uv.y-cy)/radius;float rr=dot(p,p);if(rr>1.){gl_FragColor=vec4(0.,0.,0.,1.);return;}vec3 n=vec3(p,sqrt(max(0.,1.-rr)));float c=cos(yaw),s=sin(yaw),cp=cos(pitch),sp=sin(pitch);vec3 q=vec3(n.x,n.y*cp-n.z*sp,n.y*sp+n.z*cp);q=vec3(q.x*c+q.z*s,q.y,-q.x*s+q.z*c);vec2 st=vec2(atan(q.z,q.x)/6.2831853+.5,asin(clamp(q.y,-1.,1.))/3.14159265+.5);vec3 tex=texture2D(map,st).rgb;float angle=.06;vec3 light=normalize(vec3(cos(angle),.035,-sin(angle)));float nl=dot(q,light);float diffuse=smoothstep(-.015,.07,nl)*pow(max(nl,0.),.43);float fill=.09+.14*pow(max(n.z,0.),.6);vec3 col=pow(tex,vec3(.84))*(fill+diffuse*(1.253-fill));col*=vec3(1.015,1.005,.98);float edge=1.-smoothstep(.991,1.,rr);gl_FragColor=vec4(col*opacity*edge,1.);}`;
function shader(type,src){const sh=gl.createShader(type);gl.shaderSource(sh,src);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(sh));return sh;}
let program;try{program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vert));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,frag));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('link');}catch(e){fail();return;}
gl.useProgram(program);const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const a=gl.getAttribLocation(program,'a');gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,2,gl.FLOAT,false,0,0);const uniforms={};for(const name of ['resolution','radius','cy','phase','opacity','yaw','pitch'])uniforms[name]=gl.getUniformLocation(program,name);
const texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,texture);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGB,1,1,0,gl.RGB,gl.UNSIGNED_BYTE,new Uint8Array([160,160,160]));gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.REPEAT);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);

const starVert=`precision highp float;
attribute vec3 position;attribute vec2 appearance;
uniform vec2 resolution;uniform float yaw;uniform float pitch;uniform float zoom;uniform float cy;uniform float dpr;varying float brightness;
void main(){float c=cos(yaw),s=sin(yaw),cp=cos(pitch),sp=sin(pitch);vec3 v=vec3(position.x*c-position.z*s,position.y,position.x*s+position.z*c);v=vec3(v.x,v.y*cp+v.z*sp,-v.y*sp+v.z*cp);float f=.62/zoom;float z=max(v.z,.001);vec2 screen=vec2(v.x/(z*f)*resolution.y/resolution.x,v.y/(z*f)+cy*.12);gl_Position=v.z>.05?vec4(screen,0.,1.):vec4(3.,3.,0.,1.);gl_PointSize=appearance.x*dpr;brightness=appearance.y;}`;
const starFrag=`precision highp float;
uniform vec2 resolution;uniform float radius;uniform float cy;uniform float opacity;varying float brightness;
void main(){vec2 screen=gl_FragCoord.xy/resolution*2.-1.;vec2 moonP=vec2(screen.x*resolution.x/resolution.y,screen.y-cy)/radius;if(dot(moonP,moonP)<1.003)discard;float r=length(gl_PointCoord-.5)*2.;if(r>1.)discard;float core=exp(-r*r*14.);float halo=exp(-r*r*4.)*.09;float alpha=(core+halo)*brightness*opacity;gl_FragColor=vec4(.92,.94,1.,alpha);}`;
let starProgram=null,starBuffer=null,starPosition=-1,starAppearance=-1;const starUniforms={},starCount=420;
try{starProgram=gl.createProgram();gl.attachShader(starProgram,shader(gl.VERTEX_SHADER,starVert));gl.attachShader(starProgram,shader(gl.FRAGMENT_SHADER,starFrag));gl.linkProgram(starProgram);if(!gl.getProgramParameter(starProgram,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(starProgram));for(const key of ['resolution','yaw','pitch','zoom','cy','dpr','radius','opacity'])starUniforms[key]=gl.getUniformLocation(starProgram,key);let seed=731;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};const starData=new Float32Array(starCount*5);for(let i=0;i<starCount;i++){const y=1-2*(i+.5)/starCount,theta=i*2.399963229728653+random()*.2,r=Math.sqrt(1-y*y);starData.set([r*Math.cos(theta),y,r*Math.sin(theta),2.5+random()*2.5,.22+Math.pow(random(),2)*.62],i*5);}starBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,starBuffer);gl.bufferData(gl.ARRAY_BUFFER,starData,gl.STATIC_DRAW);starPosition=gl.getAttribLocation(starProgram,'position');starAppearance=gl.getAttribLocation(starProgram,'appearance');}catch(error){console.warn('Starfield unavailable; continuing with the lunar scene.',error);starProgram=null;}

const img=new Image();img.onload=()=>{gl.bindTexture(gl.TEXTURE_2D,texture);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGB,gl.RGB,gl.UNSIGNED_BYTE,img);ready=true;note.textContent='轻触，唤醒今晚的月亮';};img.onerror=fail;img.src='moon-lro.jpg';
function resize(){const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(innerWidth*dpr);canvas.height=Math.round(innerHeight*dpr);gl.viewport(0,0,canvas.width,canvas.height);}resize();addEventListener('resize',resize);
let opened=false;const canRotate=()=>opened&&!approach&&scrollY<=0&&progress<.0001;
function frame(now){const dt=Math.min((now-last)/16.667,3)||1;last=now;const target=active?clamp(scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight)):0;progress=reduced?target:progress+(target-progress)*(1-Math.pow(.82,dt));const t=active?clamp((now-openedAt)/(reduced?150:2500)):0;phase=smooth(t);if(t===1&&!opened){opened=true;document.body.classList.remove('locked');hit.style.display='block';hit.tabIndex=0;}
if(target>.001&&!approach){approach={yaw,pitch,delta:Math.atan2(Math.sin(Math.PI/2-yaw),Math.cos(Math.PI/2-yaw))};velX=velY=0;drag=null;}if(target===0&&progress<.0001)approach=null;if(!drag&&!approach){yaw+=velX*dt;pitch=clamp(pitch+velY*dt,-1.3,1.3);velX*=Math.pow(.94,dt);velY*=Math.pow(.94,dt);}const p=smooth(progress),aspect=canvas.width/canvas.height,initial=Math.min(.55,aspect*.76),radius=initial+(2.05-initial)*p,cy=-2.43*p;const returnEase=smooth(clamp(progress/.68));const viewYaw=(approach?approach.yaw+approach.delta*returnEase:yaw)+2.88*(1-phase);const viewPitch=approach?approach.pitch*(1-returnEase):pitch;
gl.useProgram(program);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,2,gl.FLOAT,false,0,0);gl.uniform2f(uniforms.resolution,canvas.width,canvas.height);gl.uniform1f(uniforms.radius,radius);gl.uniform1f(uniforms.cy,cy);gl.uniform1f(uniforms.phase,phase);gl.uniform1f(uniforms.opacity,smooth(clamp(t*3)));gl.uniform1f(uniforms.yaw,viewYaw+p*.14);gl.uniform1f(uniforms.pitch,viewPitch+p*.1);gl.drawArrays(gl.TRIANGLES,0,6);
if(starProgram){gl.useProgram(starProgram);gl.bindBuffer(gl.ARRAY_BUFFER,starBuffer);gl.enableVertexAttribArray(starPosition);gl.vertexAttribPointer(starPosition,3,gl.FLOAT,false,20,0);gl.enableVertexAttribArray(starAppearance);gl.vertexAttribPointer(starAppearance,2,gl.FLOAT,false,20,12);gl.uniform2f(starUniforms.resolution,canvas.width,canvas.height);gl.uniform1f(starUniforms.yaw,Math.PI-(viewYaw+p*.14));gl.uniform1f(starUniforms.pitch,-(viewPitch+p*.1));gl.uniform1f(starUniforms.zoom,1+p*.18);gl.uniform1f(starUniforms.cy,cy);gl.uniform1f(starUniforms.radius,radius);gl.uniform1f(starUniforms.dpr,canvas.width/innerWidth);gl.uniform1f(starUniforms.opacity,smooth(clamp(t*2))*.8);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.drawArrays(gl.POINTS,0,starCount);gl.disable(gl.BLEND);gl.disableVertexAttribArray(starAppearance);gl.disableVertexAttribArray(starPosition);}
const diameter=radius*innerHeight;hit.style.width=diameter+'px';hit.style.height=diameter+'px';hit.style.left=(innerWidth-diameter)/2+'px';hit.style.top=(innerHeight*(1-cy)-diameter)/2+'px';hit.style.pointerEvents=canRotate()?'auto':'none';hit.style.touchAction=canRotate()?'pinch-zoom':'auto';hit.tabIndex=canRotate()?0:-1;const hint=opened?1-clamp(progress*6):0;guide.style.opacity=hint;guide.style.pointerEvents=hint>.5?'auto':'none';document.querySelector('.edition').style.opacity=active?.6*(1-p):0;const words=smooth(clamp((progress-.65)/.3));letter.style.opacity=words;letter.style.transform='translateY('+(1-words)*24+'px)';letter.setAttribute('aria-hidden',words<.1?'true':'false');replay.style.opacity=smooth(clamp((progress-.9)/.1));replay.style.pointerEvents=progress>.94?'auto':'none';replay.tabIndex=progress>.94?0:-1;raf=requestAnimationFrame(frame);}
start.addEventListener('click',()=>{if(!ready||active)return;active=true;openedAt=performance.now();start.classList.add('gone');start.tabIndex=-1;});
hit.addEventListener('touchmove',e=>{if(canRotate()&&e.touches.length===1&&e.cancelable)e.preventDefault();},{passive:false});
hit.addEventListener('wheel',e=>{if(e.ctrlKey||!canRotate())return;if(e.cancelable)e.preventDefault();e.stopPropagation();const unit=e.deltaMode===1?16:e.deltaMode===2?innerHeight:1;yaw-=clamp(e.deltaX*unit,-100,100)*.003;pitch=clamp(pitch-clamp(e.deltaY*unit,-100,100)*.003,-1.3,1.3);velX=velY=0;},{passive:false});
hit.addEventListener('pointerdown',e=>{if(!canRotate())return;if(e.cancelable)e.preventDefault();hit.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY};velX=velY=0;});
hit.addEventListener('pointermove',e=>{if(!drag||!canRotate())return;velX=(e.clientX-drag.x)*-.005;velY=(e.clientY-drag.y)*-.005;yaw+=velX;pitch=clamp(pitch+velY,-1.3,1.3);drag={x:e.clientX,y:e.clientY};hit.setAttribute('aria-valuenow',Math.round(((yaw*180/Math.PI)%360+360)%360));});for(const type of ['pointerup','pointercancel','lostpointercapture'])hit.addEventListener(type,()=>{drag=null;});
hit.addEventListener('keydown',e=>{if(!canRotate())return;if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();yaw+=e.key==='ArrowLeft'?.12:e.key==='ArrowRight'?-.12:0;pitch=clamp(pitch+(e.key==='ArrowUp'?-.12:e.key==='ArrowDown'?.12:0),-1.3,1.3);});
document.querySelector('#continue').addEventListener('click',()=>scrollTo({top:document.documentElement.scrollHeight-innerHeight,behavior:reduced?'instant':'smooth'}));
replay.addEventListener('click',()=>{scrollTo({top:0,behavior:'instant'});progress=0;phase=0;approach=null;opened=false;active=false;yaw=Math.PI/2;pitch=velX=velY=0;document.body.classList.add('locked');hit.style.display='none';start.classList.remove('gone');start.tabIndex=0;start.focus({preventScroll:true});});
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();cancelAnimationFrame(raf);fail();});canvas.addEventListener('webglcontextrestored',()=>location.reload());document.addEventListener('visibilitychange',()=>{if(document.hidden)cancelAnimationFrame(raf);else{last=performance.now();raf=requestAnimationFrame(frame);}});history.scrollRestoration='manual';scrollTo(0,0);raf=requestAnimationFrame(frame);
}
